### ISSUE TITLE
ConnectionClosedException: Server closed connection without DISCONNECT.

### ISSUE THREAD

**Issue by kenlee0305** [xmeter-net/mqtt-jmeter#114]
When i run my test plan with the number of threads exceeding 50, the test with the number of threads 51 starts getting the following exception. Does anyone know how to fix it?

Thank you 

SEVERE: Failed to establish Connection null
java.util.concurrent.ExecutionException: com.hivemq.client.mqtt.exceptions.ConnectionClosedException: Server closed connection without DISCONNECT.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at net.xmeter.samplers.mqtt.hivemq.HiveMQTTClient.connect(HiveMQTTClient.java:78)
	at net.xmeter.samplers.ConnectSampler.sample(ConnectSampler.java:91)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.hivemq.client.mqtt.exceptions.ConnectionClosedException: Server closed connection without DISCONNECT.

**Comment by Ragulpalaniappan** [comment]
Any update on this ?? I am also facing same issue

**Comment by LinhNDD1-NAL** [comment]
did you testing with csv file loaded? I am also facing same issue when I try load csv config

**Comment by alvinjoseph7** [comment]
Try increasing the setting for number of open files by typing : `ulimit -n 20000`
